run_parameters:
  experiment_name: "autoencoder-64-scheduler"
hyperparameters:
  lr: 5e-3
  epochs: 20
  latent_dim: 64
  scheduler:
    type: None #PolynomialLR  # Options: PolynomialLR, ReduceLROnPlateau, None
#    params:
#      total_iters: 20
#      power: 1.0
  optimizer:
    type: Adam
additional_trainer_params:
  auto_lr_find: true
training:
  accelerator: "gpu"
  devices: 1
